const {test}=require('node:test');
const assert=require('node:assert/strict');
const {validateBatch}=require('../.test-build/validation/index.js');
const {importCSV,parseCSV,CSV_HEADERS}=require('../.test-build/validation/csv.js');
const base={parameter:'moisture',value:'0',unit:'%',basis:'wet mass',method:'',analyte:'',qualifier:'measured',detectionLimit:'',provenance:'userReported',notes:''};
const check=(overrides={},batch={})=>validateBatch({id:'A',sampledAt:'',treatmentHistory:'',observations:[{...base,...overrides}],...batch});
const csv=(rows)=>CSV_HEADERS.join(',')+'\n'+rows;
const row=(overrides={})=>{const r={batch_id:'A',sampled_at:'',treatment_history:'',parameter:'moisture',value:'0',unit:'%',basis:'wet mass',method:'',analyte:'',qualifier:'measured',detection_limit:'',provenance:'synthetic',notes:'',...overrides};return CSV_HEADERS.map(h=>'"'+String(r[h]).replaceAll('"','""')+'"').join(',');};
test('zero is preserved and blank stays unknown',()=>{assert.equal(check().batch.measurements.moisture[0].value,0);assert.equal(check({value:''}).batch.measurements.moisture[0].value,null);});
test('reject invalid numeric strings and negative quantities',()=>{for(const value of ['NaN','Infinity','2oops','0x10','-1'])assert.ok(check({value}).errors.length);});
test('percentage endpoints accepted, above 100 rejected',()=>{assert.equal(check({value:'100'}).errors.length,0);assert.ok(check({value:'100.1'}).errors.length);});
test('unsupported units error; missing context warns',()=>{assert.ok(check({unit:'mg/L'}).errors.length);const r=check({unit:'',basis:''});assert.equal(r.errors.length,0);assert.equal(r.warnings.length,2);});
test('non-detect is not zero and retains limit',()=>{const r=check({value:'',qualifier:'notDetected',detectionLimit:'0.5'});assert.equal(r.batch.measurements.moisture[0].value,null);assert.equal(r.batch.measurements.moisture[0].detectionLimit,0.5);assert.ok(check({qualifier:'notDetected'}).errors.length);});
test('comparison qualifiers require a bound',()=>assert.ok(check({value:'',qualifier:'lessThan'}).errors.length));
test('calendar validation rejects impossible date',()=>assert.ok(check({}, {sampledAt:'2026-02-30'}).errors.length));
test('CSV handles BOM, commas, escaped quotes, multiline fields and CRLF',()=>{const text='\ufeff'+csv(row({notes:'a, "quote"\nand another line'})).replaceAll('\n','\r\n');const r=importCSV(text);assert.equal(r.errors.length,0);assert.match(r.batches[0].measurements.moisture[0].notes,/a, "quote"/);});
test('malformed quotes reject file',()=>{assert.throws(()=>parseCSV('a,"b'));assert.throws(()=>parseCSV('"a"oops,b'));});
test('invalid headers and column counts rejected',()=>{assert.ok(importCSV('a,b\n1,2').errors.length);assert.ok(importCSV(csv('A,2')).errors.length);});
test('multiple batches and repeated observations preserved',()=>{const r=importCSV(csv([row(),row({method:'repeat'}),row({batch_id:'B'})].join('\n')));assert.equal(r.errors.length,0);assert.equal(r.batches.length,2);assert.equal(r.batches[0].measurements.moisture.length,2);});
test('metadata conflict and invalid parameter get row numbers',()=>{const r=importCSV(csv([row(),row({sampled_at:'2026-01-01'}),row({batch_id:'B',parameter:'bogus'})].join('\n')));assert.deepEqual(r.errors.map(e=>e.row),[3,4]);});
test('row limit enforced',()=>assert.ok(importCSV(csv(Array(1001).fill(row()).join('\n'))).errors.length));
test('downloadable example validates',()=>{const fs=require('node:fs');const r=importCSV(fs.readFileSync('public/samples/synthetic-batches.csv','utf8'));assert.equal(r.errors.length,0);assert.equal(r.batches.length,2);});
